### ISSUE TITLE
팀원 마지막 한 분 더 구합니다.

### ISSUE THREAD

**Issue by wogur0602** [swsnu/swppfall2017#15]
현재 저희 팀에 두 명 있고, 함께 하실 팀원 두 분 더 구합니다.
같이 하실 분들은 댓글 달아주세요~
Our team is looking for two another teammates.
If you want to join, please leave a comment.

**Comment by dldjwls3** [comment]
안녕하세요! 혹시 아직 자리가 있으면 팀원이 되고 싶습니다! @wogur0602

**Comment by wogur0602** [comment]
네 자리 있습니다!!!! chlwogur0413@snu.ac.kr로 학번/이름/전화번호 보내주세요~ @dldjwls3

**Comment by wogur0602** [comment]
마지막 한 분 모집합니다. 댓글 달아주세요.
Due to the joining of new personnel, our team seeks the last team member.
If you interested, please leave a comment.

**Comment by dongyeob94** [comment]
팀 자리 남았으면 들어가도 될까요?

**Comment by wogur0602** [comment]
넵 chlwogur0413@snu.ac.kr로 학번/이름/전화번호 보내주세요 @dongyeob94
