### ISSUE TITLE
[Team] last member recruitment (마지막 팀원 한 명 모집합니다!)

### ISSUE THREAD

**Issue by jhbaang** [swsnu/swppfall2017#16]
아직 팀을 구하지 못하셨다면, 저희와 함께 재밌게 프로젝트 해보시는건 어떠신가요? 이미 세 명이 모아져있기에, 마지막 한 분을 모집합니다. 관심있는분은 코멘트남겨주시면 감사하겠습니다. :-)

Hi, We are a team of three. We are waiting for last member to join us who can enjoy solving some interesting projects and problems in software development together. 
Please leave a comment if you are interested in!
Thankyou

**Comment by SoheeLee** [comment]
안녕하세요! 아직 자리가 있나요? 함께 해도 될까요?

**Comment by jhbaang** [comment]
환영합니다! 제 이메일 apooapooar@gmail.com으로 연락처 또는 카카오톡 아이디를보내주실 수 있으신가요?

**Comment by jhbaang** [comment]
@SoheeLee
