### ISSUE TITLE
Looking for Teammate

### ISSUE THREAD

**Issue by hjun555** [swsnu/swppfall2017#17]
현재 두 명인 상태입니다.  맨땅에 헤딩할 준비가 된 두명과 한 학기동안 같이 열심히 프로젝트 해나갈 팀원을 찾습니다!

 Hello we are looking for teammate who can work hard with us. we are ready for it. Thank you.

**Comment by leejisup** [comment]
아직 자리 있으면 참가할게요~

**Comment by hjun555** [comment]
네 hjun555 로 카톡주세요

**Comment by hjun555** [comment]
그리고 아직 한 분 더 찾고 있습니다!

**Comment by scintilla269** [comment]
저도 같이 할 수 있을까요?

**Comment by hjun555** [comment]
네! hjun555로 카톡주세요
