### ISSUE TITLE
혹시 아직 팀이 없으신분 계신가요?

### ISSUE THREAD

**Issue by lkys221** [swsnu/swppfall2017#21]
아직 팀원이 3명이라 같이 하실 분 계시면 연락주세요

**Comment by cloudytheconqueror** [comment]
저 아직 팀에 안 들어갔는데 들어갈 수 있을까요?

**Comment by lkys221** [comment]
네!  성함, 학번, 깃아이디 그리고 폰번호 lkys221@snu.ac.kr로 보내주세요~
