### ISSUE TITLE
팀원 구해요

### ISSUE THREAD

**Issue by yeonwooKim** [swsnu/swppfall2017#3]
컴퓨터공학부 14학번 김연우입니다.
같은 14학번 현우랑 팀 하실 두 분 구해요~

**Comment by KimHyeonwoo** [comment]
[Translate]
we are looking for two wonderful teammate!!
please reply :)

**Comment by uhurubrahms** [comment]
혹시 팀원 다 모였나요? 저 들어갈 자리 있을까요??

**Comment by KimHyeonwoo** [comment]
와와 좋아요!! 마지막 한 분 구해요 :)

**Comment by paintthetiger** [comment]
혹시 다 모이셨나요?? 저도 함께해도 괜찮을까요??

**Comment by KimHyeonwoo** [comment]
와와 좋아요!!

**Comment by lucienmenassol** [comment]
Hey !
We are a group of three exchange student looking for a 4th partner, don't hesitate if you're interested !
The only requirement is to speak/write in english because some of us don't speak korean ^^

**Comment by yeonwooKim** [comment]
@uhurubrahms @paintthetiger 
nokjiwon96@gmail.com 으로 이름, 학번, 전화번호 보내주시면 감사하겠습니다.
project proposal 전에 만나서 프로젝트 뭐할지 얘기해봐요!
