### ISSUE TITLE
팀원 구합니다.

### ISSUE THREAD

**Issue by jyeoniii** [swsnu/swppfall2017#8]
현재 저 포함 두 명 있고, 함께 하실 다른 팀원 두 분 구합니다!
관심 있으신 분 댓글 달아주세요~ :)

We are looking for two teammates! If you're interested, feel free to leave comment.

**Comment by SoheeLee** [comment]
혹시 자리가 아직 다 안 찼나요? 제가 들어갈 자리가 있을까요?

**Comment by 93lemondrops** [comment]
저희 두 명 있어요!

**Comment by jyeoniii** [comment]
@93lemondrops 우와 좋아요! 카톡 `jyeoni222`로 연락 부탁드립니다 :D
